### ISSUE TITLE
Everything works fine but 1 small issue:

### ISSUE THREAD

**Issue by rrhyast** [maecry/csgo-cunny#5]
![csgo_lDwnLWlL6p](https://user-images.githubusercontent.com/62977195/218175537-b69225f8-e5f5-405c-ab8d-0ac3f03ef0a0.png)

Even after installing the Font & Visual C++ library, this error still exists. I don't know how to fix it, it crashes the game when you enable name in visuals.

**Comment by maecry** [comment]
![uhm](https://too.lewd.se/750c2e31f776_opera_GBhPD4Vu85.png)

or just change ArialUni.ttf to something else

**Comment by maecry** [comment]
if you wonder why i'm not turning it into a byte array then it's a big ass font so no
